module.exports = {
    'trance': true,
    'techno': true,
    'house': true,
    'club': true,
    '50s': true,
    '80s': true,
    '60s': true,
    '70s': true,
    'baroque pop': true,
    'oldies': true,
    'soul': true,
    'garage rock': true,
    'dub': true,
    'drum and bass': true,
    'dubstep': true,
    'hip-hop': true,
    'hiphop': true,
    'rap': true,
    'hip hop': true,
    'grime': true,
    'folk': true,
    'lo-fi': true,
    'funk': true,
    'blues': true,
    'new wave': true,
    'rock and roll': true,
    'rock n roll': true,
    'rockabilly': true,
    'newage': true,
    'neoclassical': true,
    'classical': true,
    'christmas': true,
    'comedy': true,
    'stand-up': true,
    'kabarett': true,
    "rock'n'roll": true,
    'tango': true,
    'polkka': true,
    'valssi': true,
    'hanuri': true,
    'humour': true,
    'reggae': true,
    '1950s': true,
    '1960s': true,
    '1970s': true,
    'rnb': true,
    'disco': true,
    'nusoul': true,
    'folklor': true,
    'newwave': true,
    'jazz': true,
    'avant-garde': true,
    'fusion': true,
    'christianrock': true,
    'horrorpunk': true,
    'rockandroll': true,
    'folkrock': true,
    'edm': true,
    'grunge': true,
    'groove metal': true,
    'punk rock': true,
    'punk': true,
    'dim': true,
    'tech house': true,
    'Rave': true,
    'happy hardcore': true,
    'minimal': true,
    'Idm': true,
    'big beat': true,
    'Jumpstyle': true,
    'hardstyle': true,
    '8-bit': true,
    'new rave': true,
    'electroclash': true,
    'afrobeat': true,
    'post-nerdcore': true,
    'littlestar': true,
    'Afro-pop': true,
    'African': true,
    'african': true,
    'eurobeat': true,
    'idm': true,
    'fip': true,
    'bluesrock': true,
    'ska': true,
    'skapunk': true,
    'electrohouse': true,
    'chansonfrancaise': true,
    'frenchhiphop': true,
    'baby': true,
    'childrensongs': true
}

